name: Scheduled Auto Merge for Renovate PRs

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:        # Allows manual run from GitHub UI

jobs:
  auto-merge-scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: List open PRs
        uses: actions/github-script@v7
        id: list-prs
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            });

            const renovatePRs = prs.data.filter(pr =>
              pr.user.login === 'renovate[bot]' &&
              pr.labels.some(label => label.name === 'automerge')
            );

            return renovatePRs.map(pr => pr.number);

      - name: Enable auto-merge on qualifying PRs
        if: steps.list-prs.outputs.result != '[]'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          pull-request-number: ${{ fromJson(steps.list-prs.outputs.result)[0] }}

      - name: Enable auto-merge on remaining PRs (if more than one)
        if: steps.list-prs.outputs.result != '[]'
        run: |
          prs=${{ steps.list-prs.outputs.result }}
          echo "$prs" | jq '.[1:][]' | while read pr; do
            echo "Enabling auto-merge on PR #$pr"
            gh pr merge "$pr" --squash --auto
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
