name: Scheduled Auto Merge for Renovate PRs

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:        # Allows manual triggering

jobs:
  auto-merge-renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Find Renovate PRs with 'auto merge' label
        id: find-renovate-prs
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              per_page: 100
            });

            const eligible = prs.data.filter(pr =>
              pr.user.login === "renovate[bot]" &&
              pr.labels.some(label => label.name === "automerge")
            );

            core.setOutput("prs", JSON.stringify(eligible.map(pr => pr.number)));

      - name: Enable auto-merge on matching PRs
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = JSON.parse('${{ steps.find-renovate-prs.outputs.prs }}');
            const repo = context.repo;

            for (const number of prs) {
              console.log(`Enabling auto-merge on PR #${number}`);
              try {
                await github.graphql(`
                  mutation($input: EnablePullRequestAutoMergeInput!) {
                    enablePullRequestAutoMerge(input: $input) {
                      pullRequest {
                        number
                        autoMergeRequest {
                          enabledBy {
                            login
                          }
                        }
                      }
                    }
                  }
                `, {
                  input: {
                    pullRequestId: (await github.rest.pulls.get({
                      owner: repo.owner,
                      repo: repo.repo,
                      pull_number: number
                    })).data.node_id,
                    mergeMethod: "SQUASH"
                  }
                });
              } catch (error) {
                console.warn(`Failed to enable auto-merge on PR #${number}: ${error.message}`);
              }
            }
