name: Auto Merge Renovate PRs

on:
  pull_request:
    types: [labeled, synchronize, reopened]

jobs:
  auto-merge:
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Auto-merge Renovate PRs
        uses: "peter-evans/enable-pull-request-automerge@v3"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

      - name: Merge PR
        if: contains(github.event.pull_request.labels.*.name, 'automerge') && github.event.pull_request.mergeable_state == 'clean'
        run: gh pr merge "$PR_URL" --squash --auto
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
